### ISSUE TITLE
Victus heart textures not showing

### ISSUE THREAD

**Issue by dialexneves** [glisco03/victus#18]
I am currently playing a Fabric modpack 1.19.2 (Prominence + extra) with about 470+ mods including Victus.
Some of them, including resource packs, change the player's interface appearence. This might be messing with the victus mod by not showing the heart types on the health bar. The issue is, I don't know what specific mods or resource packs cause the interference. It makes it hard to keep up with what types I have consumed and their respective positions. Im not sure if something can be done regarding this, but maybe compatibility tweaks might fix it.

Mods or Resourcepacks that might interfere with victus:
- OptiGUI mod
- MandalasGUI resource pack
(I could not resolve the issue by removing either)
- Some unknown mod that changes the interface and I cannot identify.

This is a great mod and I'm having great fun with it. Keep it up.

**Comment by gliscowo** [comment]
I can certainly understand that this is problematic, but the support period for 1.19.2 has ended a long time ago and I simply don't have the time to keep investigating issues on old versions of the game and mod. What I can tell you is that Health Overlay (or something equivalent) tends to mess with Victus - and that's also not really resolvable other than by removing the mod since you *need* to be able to see all of your hearts at all times when using Victus

Cheers
